# See http://www.appveyor.com/docs/appveyor-yml for many more options

image: Visual Studio 2019

install:
  - ps: .\module.build.ps1 -InstallDependencies -Verbose

build_script:
  - ps: .\module.build.ps1
# Test with PS core
  - pwsh: .\module.build.ps1 test
# Upload code coverage report to CodeCov.io
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "$($Script:CodeCoverageFile)"