# See http://www.appveyor.com/docs/appveyor-yml for many more options
# Use VS2019 image
image: Visual Studio 2019

#Enable RDP access when troubleshooting
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: .\module.build.ps1 -InstallDependencies -Verbose

build_script:
  - ps: .\module.build.ps1
# Test with PS core
#  - pwsh: .\module.build.ps1 test; exit 0

after_build:
  # Upload Pester and ScriptAnalyzer output; leverage Add-TestResultToAppVeyor from BuildHelpers module
  - ps: Add-TestResultToAppVeyor -TestFile (Get-ChildItem '.\BuildOutput\*.xml' -Exclude 'CodeCoverage_*')
# Upload code coverage report to CodeCov.io
  - ps: Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh; $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH; bash codecov.sh -f ""CodeCoverage*.xml"" -A "-s"