# See http://www.appveyor.com/docs/appveyor-yml for many more options
# Use VS2019 image
image: Visual Studio 2019

cache:
  - BuildOutput\modules                 # downloaded PowerShell modules

#Enable RDP access when troubleshooting using environment variables APPVEYOR_RDP_ENABLE and APPVEYOR_RDP_BLOCK
#on_finish:
after_build:
  - ps: |
      $EnableRDP=$False;$Null=[bool]::TryParse($Env:APPVEYOR_RDP_ENABLE,[ref]$EnableRDP)
      $BlockRDP=$False;$Null=[bool]::TryParse($Env:APPVEYOR_RDP_BLOCK,[ref]$BlockRDP)
      if ($EnableRDP) {Invoke-Expression ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))}

install:
  - ps: .\module.build.ps1 -InstallDependencies

build_script:
  - ps: .\module.build.ps1
# Test with PS core
#  - pwsh: .\module.build.ps1 test; exit 0