# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: 1
  displayName: Init and run build
  steps:
  - powershell: |
      & "$($Env:BUILD_SOURCESDIRECTORY)\module.build.ps1" -InstallDependencies -Verbose
      & "$($Env:BUILD_SOURCESDIRECTORY)\module.build.ps1"
    displayName: Init and run build
- job: 2
  displayname: Publish results
  condition: succeededOrFailed()
  steps:
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: |
        BuildOutput/ScriptAnalyzer*.xml
        BuildOutput/TestResults*.xml
      testRunTitle: 'PSScriptAnalyzer and Pester'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/BuildOutput/CodeCoverage*.xml'
      pathToSources: '$(System.DefaultWorkingDirectory)'
