# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: '.\module.build.ps1'
    arguments: '-InstallDependencies'
    script: .\module.build.ps1 -InstallDependencies
- task: PowerShell@2
  inputs:
    filePath: '.\module.build.ps1'
    script: .\module.build.ps1