# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    & "$($Env:BUILD_SOURCESDIRECTORY)\module.build.ps1" -InstallDependencies -Verbose
    & "$($Env:BUILD_SOURCESDIRECTORY)\module.build.ps1"
  displayName: Init and run build
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/BuildOutput/CodeCoverage*.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)'
  condition: succeededOrFailed()
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: |
      BuildOutput/ScriptAnalyzer*.xml
    mergeTestResults: false
    testRunTitle: 'PSScriptAnalyzer'
  condition: succeededOrFailed()
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: |
      BuildOutput/TestResults*.xml
    mergeTestResults: false
    testRunTitle: 'Pester'
  condition: succeededOrFailed()