# Module manifest for module 'chronometer'
# Generated by: Maarten Piederiet
# Generated on: 2/2/2017

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'mypsbuildtest.psm1'
    
    # Version number of this module.
    ModuleVersion = '1.0.0'
    
    # ID used to uniquely identify this module
    GUID = 'd1949146-7891-49ae-9041-57673393c734'
    
    # Author of this module
    Author = 'Maarten Piederiet'
    
    # Copyright statement for this module
    Copyright = '(c) 2019 Maarten Piederiet. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'Just a test to start with AppVeyor and Invoke-Build'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @('Start-DoNothing')
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()
    
    # Variables to export from this module
    #VariablesToExport = '*'
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('test','module','measure','performance')
    
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/mpiederiet/MyPSBuildTest/blob/master/LICENSE'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/mpiederiet/MyPSBuildTest'
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    }
